name: Demo Workflow

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Print to console
              run: echo "Hello, world!"
            - name: Checkout code
              uses: actions/checkout@v4
            - name: List files and folders
              run: ls